/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VendasRouteImport } from './routes/vendas'
import { Route as TermosRouteImport } from './routes/termos'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AssinarRouteImport } from './routes/assinar'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedTutorialRouteImport } from './routes/_authenticated/tutorial'
import { Route as AuthenticatedSupportRouteImport } from './routes/_authenticated/support'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedBuyCreditsRouteImport } from './routes/_authenticated/buy-credits'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiPublicExtensionVersionRouteImport } from './routes/api/public/extension-version'
import { Route as ApiPublicCronCreditsRenewRouteImport } from './routes/api/public/cron-credits-renew'
import { Route as ApiPublicAsaasWebhookRouteImport } from './routes/api/public/asaas-webhook'
import { Route as ApiPublicAnnouncementRouteImport } from './routes/api/public/announcement'
import { Route as ApiPublicAiReplyRouteImport } from './routes/api/public/ai-reply'
import { Route as AuthenticatedAdminUsageRouteImport } from './routes/_authenticated/admin.usage'
import { Route as AuthenticatedAdminTenantsRouteImport } from './routes/_authenticated/admin.tenants'
import { Route as AuthenticatedAdminSupportRouteImport } from './routes/_authenticated/admin.support'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated/admin.plans'
import { Route as AuthenticatedAdminMaintenanceRouteImport } from './routes/_authenticated/admin.maintenance'
import { Route as AuthenticatedAdminInvitesRouteImport } from './routes/_authenticated/admin.invites'
import { Route as AuthenticatedAdminBrandingRouteImport } from './routes/_authenticated/admin.branding'
import { Route as AuthenticatedAdminAnnouncementsRouteImport } from './routes/_authenticated/admin.announcements'
import { Route as AuthenticatedAdminAiCreditsRouteImport } from './routes/_authenticated/admin.ai-credits'
import { Route as AuthenticatedAdminAiConfigRouteImport } from './routes/_authenticated/admin.ai-config'

const VendasRoute = VendasRouteImport.update({
  id: '/vendas',
  path: '/vendas',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinarRoute = AssinarRouteImport.update({
  id: '/assinar',
  path: '/assinar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTutorialRoute = AuthenticatedTutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSupportRoute = AuthenticatedSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBuyCreditsRoute = AuthenticatedBuyCreditsRouteImport.update({
  id: '/buy-credits',
  path: '/buy-credits',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiPublicExtensionVersionRoute =
  ApiPublicExtensionVersionRouteImport.update({
    id: '/api/public/extension-version',
    path: '/api/public/extension-version',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronCreditsRenewRoute =
  ApiPublicCronCreditsRenewRouteImport.update({
    id: '/api/public/cron-credits-renew',
    path: '/api/public/cron-credits-renew',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAsaasWebhookRoute = ApiPublicAsaasWebhookRouteImport.update({
  id: '/api/public/asaas-webhook',
  path: '/api/public/asaas-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnnouncementRoute = ApiPublicAnnouncementRouteImport.update({
  id: '/api/public/announcement',
  path: '/api/public/announcement',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAiReplyRoute = ApiPublicAiReplyRouteImport.update({
  id: '/api/public/ai-reply',
  path: '/api/public/ai-reply',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminUsageRoute = AuthenticatedAdminUsageRouteImport.update({
  id: '/usage',
  path: '/usage',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminTenantsRoute =
  AuthenticatedAdminTenantsRouteImport.update({
    id: '/tenants',
    path: '/tenants',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSupportRoute =
  AuthenticatedAdminSupportRouteImport.update({
    id: '/support',
    path: '/support',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminMaintenanceRoute =
  AuthenticatedAdminMaintenanceRouteImport.update({
    id: '/maintenance',
    path: '/maintenance',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInvitesRoute =
  AuthenticatedAdminInvitesRouteImport.update({
    id: '/invites',
    path: '/invites',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBrandingRoute =
  AuthenticatedAdminBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAnnouncementsRoute =
  AuthenticatedAdminAnnouncementsRouteImport.update({
    id: '/announcements',
    path: '/announcements',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAiCreditsRoute =
  AuthenticatedAdminAiCreditsRouteImport.update({
    id: '/ai-credits',
    path: '/ai-credits',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAiConfigRoute =
  AuthenticatedAdminAiConfigRouteImport.update({
    id: '/ai-config',
    path: '/ai-config',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assinar': typeof AssinarRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/vendas': typeof VendasRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/buy-credits': typeof AuthenticatedBuyCreditsRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tutorial': typeof AuthenticatedTutorialRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/ai-config': typeof AuthenticatedAdminAiConfigRoute
  '/admin/ai-credits': typeof AuthenticatedAdminAiCreditsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/api/public/ai-reply': typeof ApiPublicAiReplyRoute
  '/api/public/announcement': typeof ApiPublicAnnouncementRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/cron-credits-renew': typeof ApiPublicCronCreditsRenewRoute
  '/api/public/extension-version': typeof ApiPublicExtensionVersionRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assinar': typeof AssinarRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/vendas': typeof VendasRoute
  '/buy-credits': typeof AuthenticatedBuyCreditsRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/support': typeof AuthenticatedSupportRoute
  '/tutorial': typeof AuthenticatedTutorialRoute
  '/invite/$token': typeof InviteTokenRoute
  '/admin/ai-config': typeof AuthenticatedAdminAiConfigRoute
  '/admin/ai-credits': typeof AuthenticatedAdminAiCreditsRoute
  '/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/support': typeof AuthenticatedAdminSupportRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/api/public/ai-reply': typeof ApiPublicAiReplyRoute
  '/api/public/announcement': typeof ApiPublicAnnouncementRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/cron-credits-renew': typeof ApiPublicCronCreditsRenewRoute
  '/api/public/extension-version': typeof ApiPublicExtensionVersionRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/assinar': typeof AssinarRoute
  '/login': typeof LoginRoute
  '/privacidade': typeof PrivacidadeRoute
  '/reset-password': typeof ResetPasswordRoute
  '/termos': typeof TermosRoute
  '/vendas': typeof VendasRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/buy-credits': typeof AuthenticatedBuyCreditsRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/support': typeof AuthenticatedSupportRoute
  '/_authenticated/tutorial': typeof AuthenticatedTutorialRoute
  '/invite/$token': typeof InviteTokenRoute
  '/_authenticated/admin/ai-config': typeof AuthenticatedAdminAiConfigRoute
  '/_authenticated/admin/ai-credits': typeof AuthenticatedAdminAiCreditsRoute
  '/_authenticated/admin/announcements': typeof AuthenticatedAdminAnnouncementsRoute
  '/_authenticated/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/_authenticated/admin/invites': typeof AuthenticatedAdminInvitesRoute
  '/_authenticated/admin/maintenance': typeof AuthenticatedAdminMaintenanceRoute
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/support': typeof AuthenticatedAdminSupportRoute
  '/_authenticated/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/_authenticated/admin/usage': typeof AuthenticatedAdminUsageRoute
  '/api/public/ai-reply': typeof ApiPublicAiReplyRoute
  '/api/public/announcement': typeof ApiPublicAnnouncementRoute
  '/api/public/asaas-webhook': typeof ApiPublicAsaasWebhookRoute
  '/api/public/cron-credits-renew': typeof ApiPublicCronCreditsRenewRoute
  '/api/public/extension-version': typeof ApiPublicExtensionVersionRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assinar'
    | '/login'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/vendas'
    | '/admin'
    | '/buy-credits'
    | '/checkout'
    | '/dashboard'
    | '/support'
    | '/tutorial'
    | '/invite/$token'
    | '/admin/ai-config'
    | '/admin/ai-credits'
    | '/admin/announcements'
    | '/admin/branding'
    | '/admin/invites'
    | '/admin/maintenance'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/tenants'
    | '/admin/usage'
    | '/api/public/ai-reply'
    | '/api/public/announcement'
    | '/api/public/asaas-webhook'
    | '/api/public/cron-credits-renew'
    | '/api/public/extension-version'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assinar'
    | '/login'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/vendas'
    | '/buy-credits'
    | '/checkout'
    | '/dashboard'
    | '/support'
    | '/tutorial'
    | '/invite/$token'
    | '/admin/ai-config'
    | '/admin/ai-credits'
    | '/admin/announcements'
    | '/admin/branding'
    | '/admin/invites'
    | '/admin/maintenance'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/support'
    | '/admin/tenants'
    | '/admin/usage'
    | '/api/public/ai-reply'
    | '/api/public/announcement'
    | '/api/public/asaas-webhook'
    | '/api/public/cron-credits-renew'
    | '/api/public/extension-version'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/assinar'
    | '/login'
    | '/privacidade'
    | '/reset-password'
    | '/termos'
    | '/vendas'
    | '/_authenticated/admin'
    | '/_authenticated/buy-credits'
    | '/_authenticated/checkout'
    | '/_authenticated/dashboard'
    | '/_authenticated/support'
    | '/_authenticated/tutorial'
    | '/invite/$token'
    | '/_authenticated/admin/ai-config'
    | '/_authenticated/admin/ai-credits'
    | '/_authenticated/admin/announcements'
    | '/_authenticated/admin/branding'
    | '/_authenticated/admin/invites'
    | '/_authenticated/admin/maintenance'
    | '/_authenticated/admin/plans'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/support'
    | '/_authenticated/admin/tenants'
    | '/_authenticated/admin/usage'
    | '/api/public/ai-reply'
    | '/api/public/announcement'
    | '/api/public/asaas-webhook'
    | '/api/public/cron-credits-renew'
    | '/api/public/extension-version'
    | '/_authenticated/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AssinarRoute: typeof AssinarRoute
  LoginRoute: typeof LoginRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  TermosRoute: typeof TermosRoute
  VendasRoute: typeof VendasRoute
  InviteTokenRoute: typeof InviteTokenRoute
  ApiPublicAiReplyRoute: typeof ApiPublicAiReplyRoute
  ApiPublicAnnouncementRoute: typeof ApiPublicAnnouncementRoute
  ApiPublicAsaasWebhookRoute: typeof ApiPublicAsaasWebhookRoute
  ApiPublicCronCreditsRenewRoute: typeof ApiPublicCronCreditsRenewRoute
  ApiPublicExtensionVersionRoute: typeof ApiPublicExtensionVersionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/vendas': {
      id: '/vendas'
      path: '/vendas'
      fullPath: '/vendas'
      preLoaderRoute: typeof VendasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinar': {
      id: '/assinar'
      path: '/assinar'
      fullPath: '/assinar'
      preLoaderRoute: typeof AssinarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tutorial': {
      id: '/_authenticated/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof AuthenticatedTutorialRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/support': {
      id: '/_authenticated/support'
      path: '/support'
      fullPath: '/support'
      preLoaderRoute: typeof AuthenticatedSupportRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/buy-credits': {
      id: '/_authenticated/buy-credits'
      path: '/buy-credits'
      fullPath: '/buy-credits'
      preLoaderRoute: typeof AuthenticatedBuyCreditsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/public/extension-version': {
      id: '/api/public/extension-version'
      path: '/api/public/extension-version'
      fullPath: '/api/public/extension-version'
      preLoaderRoute: typeof ApiPublicExtensionVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron-credits-renew': {
      id: '/api/public/cron-credits-renew'
      path: '/api/public/cron-credits-renew'
      fullPath: '/api/public/cron-credits-renew'
      preLoaderRoute: typeof ApiPublicCronCreditsRenewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/asaas-webhook': {
      id: '/api/public/asaas-webhook'
      path: '/api/public/asaas-webhook'
      fullPath: '/api/public/asaas-webhook'
      preLoaderRoute: typeof ApiPublicAsaasWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/announcement': {
      id: '/api/public/announcement'
      path: '/api/public/announcement'
      fullPath: '/api/public/announcement'
      preLoaderRoute: typeof ApiPublicAnnouncementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/ai-reply': {
      id: '/api/public/ai-reply'
      path: '/api/public/ai-reply'
      fullPath: '/api/public/ai-reply'
      preLoaderRoute: typeof ApiPublicAiReplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/usage': {
      id: '/_authenticated/admin/usage'
      path: '/usage'
      fullPath: '/admin/usage'
      preLoaderRoute: typeof AuthenticatedAdminUsageRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tenants': {
      id: '/_authenticated/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AuthenticatedAdminTenantsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/support': {
      id: '/_authenticated/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AuthenticatedAdminSupportRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/maintenance': {
      id: '/_authenticated/admin/maintenance'
      path: '/maintenance'
      fullPath: '/admin/maintenance'
      preLoaderRoute: typeof AuthenticatedAdminMaintenanceRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invites': {
      id: '/_authenticated/admin/invites'
      path: '/invites'
      fullPath: '/admin/invites'
      preLoaderRoute: typeof AuthenticatedAdminInvitesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/branding': {
      id: '/_authenticated/admin/branding'
      path: '/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AuthenticatedAdminBrandingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/announcements': {
      id: '/_authenticated/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AuthenticatedAdminAnnouncementsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai-credits': {
      id: '/_authenticated/admin/ai-credits'
      path: '/ai-credits'
      fullPath: '/admin/ai-credits'
      preLoaderRoute: typeof AuthenticatedAdminAiCreditsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai-config': {
      id: '/_authenticated/admin/ai-config'
      path: '/ai-config'
      fullPath: '/admin/ai-config'
      preLoaderRoute: typeof AuthenticatedAdminAiConfigRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAiConfigRoute: typeof AuthenticatedAdminAiConfigRoute
  AuthenticatedAdminAiCreditsRoute: typeof AuthenticatedAdminAiCreditsRoute
  AuthenticatedAdminAnnouncementsRoute: typeof AuthenticatedAdminAnnouncementsRoute
  AuthenticatedAdminBrandingRoute: typeof AuthenticatedAdminBrandingRoute
  AuthenticatedAdminInvitesRoute: typeof AuthenticatedAdminInvitesRoute
  AuthenticatedAdminMaintenanceRoute: typeof AuthenticatedAdminMaintenanceRoute
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSupportRoute: typeof AuthenticatedAdminSupportRoute
  AuthenticatedAdminTenantsRoute: typeof AuthenticatedAdminTenantsRoute
  AuthenticatedAdminUsageRoute: typeof AuthenticatedAdminUsageRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAiConfigRoute: AuthenticatedAdminAiConfigRoute,
  AuthenticatedAdminAiCreditsRoute: AuthenticatedAdminAiCreditsRoute,
  AuthenticatedAdminAnnouncementsRoute: AuthenticatedAdminAnnouncementsRoute,
  AuthenticatedAdminBrandingRoute: AuthenticatedAdminBrandingRoute,
  AuthenticatedAdminInvitesRoute: AuthenticatedAdminInvitesRoute,
  AuthenticatedAdminMaintenanceRoute: AuthenticatedAdminMaintenanceRoute,
  AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSupportRoute: AuthenticatedAdminSupportRoute,
  AuthenticatedAdminTenantsRoute: AuthenticatedAdminTenantsRoute,
  AuthenticatedAdminUsageRoute: AuthenticatedAdminUsageRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedBuyCreditsRoute: typeof AuthenticatedBuyCreditsRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedSupportRoute: typeof AuthenticatedSupportRoute
  AuthenticatedTutorialRoute: typeof AuthenticatedTutorialRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedBuyCreditsRoute: AuthenticatedBuyCreditsRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedSupportRoute: AuthenticatedSupportRoute,
  AuthenticatedTutorialRoute: AuthenticatedTutorialRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AssinarRoute: AssinarRoute,
  LoginRoute: LoginRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  TermosRoute: TermosRoute,
  VendasRoute: VendasRoute,
  InviteTokenRoute: InviteTokenRoute,
  ApiPublicAiReplyRoute: ApiPublicAiReplyRoute,
  ApiPublicAnnouncementRoute: ApiPublicAnnouncementRoute,
  ApiPublicAsaasWebhookRoute: ApiPublicAsaasWebhookRoute,
  ApiPublicCronCreditsRenewRoute: ApiPublicCronCreditsRenewRoute,
  ApiPublicExtensionVersionRoute: ApiPublicExtensionVersionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
