// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kmzfgxqpldgmppculkje.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttemZneHFwbGRnbXBwY3Vsa2plIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODA0OTQ5MDAsImV4cCI6MjA5NjA3MDkwMH0.FPhGzQz-X0AIB_SpzNE7C73HSTS0P8w2DvXq2ElM7oo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});